# Einführung

## Freier Wille? - Ja, Nein, Vielleicht, Egal

Im Rahmen dieser Seminarsitzung möchten wir uns mit euch auf kreative Art und Weise mit folgende Fragestellungen auseinandersetzen:

> *(1) Existiert der freie Wille wirklich oder ist er schlicht eine Illusion?*

> *(2) Kann unsere Gesellschaft nur dann funktionieren, wenn der freie Wille existiert?*

> *(3) Falls der freie Wille nicht existieren sollte, müssen wir an dessen Existenz glauben, um das Funktionieren unserer Gesellschaft sicherstellen zu können?*

Die kritische Betrachtung solch abstrakter Fragestellungen ist leider oft alles andere als leicht. Aus diesem Grund wollen wir mit euch die besagten Fragestellungen anhand eines deutlich greifbareren Konzeptes kritisch diskutieren: der **Schuldfähigkeit**.

## Freier Wille und Schuldfähigkeit

Bevor wir uns an der Beantwortung der obigen Fragen versuchen, lasst uns zuerst eine Antwort auf **die Frage** finden, **die immer die erste sein sollte**:

> *Wieso ist die Antwort auf diese Frage(n) von Relevanz?*

Zur Beantwortung der **ersten Frage** lasst uns einige **potentielle** Implikationen von zwei Antwortmöglichkeiten für Frage (1) im Hinblick auf die Schuldfähigkeit einer kriminellen Person betrachten.

**Der freie Wille existiert.**

-   Personen sind generell dazu fähig, sich bewusst dafür oder dagegen zu entscheiden ein bestimmtes Verhalten zu zeigen.

    -   Personen sind im rechtlichen Sinne generell als **schuldfähig** zu betrachten.

-   Personen sind **verantwortlich** für das Verhalten, welches sie bewusst zeigen bzw. nicht zeigen.

    -   Personen **tragen** die **Schuld** für ihre kriminellen Handlungen bzw. für das kriminelle Unterlassen bestimmter Handlungen.

**Der freie Wille existiert nicht.**

-   Ob Personen ein bestimmtes Verhalten zeigen oder nicht, hängt **nicht** von bewussten Entscheidungsprozessen ab.

    -   Personen sind im rechtlichen Sinne generell als **nicht schuldfähi**g zu betrachten.

```{=html}
<!-- -->
```
-   Personen sind **nicht verantwortlich** für das Verhalten, welches sie zeigen bzw. nicht zeigen.

    -   Personen **tragen keine Schuld** für ihre kriminellen Handlungen bzw. für das kriminelle Unterlassen bestimmter Handlungen.

Eine mögliche Antwort auf die **erste Frage** lautet dementsprechend:

> *Die Antworten auf Fragen (1) bis (3) sind von Relevanz, da diese beispielsweise bedeutende Implikationen für die Rechtsprechung in unserer Gesellschaft haben können.*
