# Beweismittel der Verteidigung {#defence-evidence}

Eure Position als Verteidigung ist die folgende:

> *Daniel B. war zum Zeitpunkt der Tat nicht schuldfähig und ist daher frei zu sprechen.*

Eure Position basiert auf der Annahme, dass Daniel B. **keinen** **freien Willen** besitzt und sich daher **nicht** **bewusst** dazu entscheiden konnte Sigmund F. zu ermorden.

Nutzt bitte die folgenden Textausschnitte, um eine sinnvolle Argumentation aufzubauen. Selbstverständlich könnt ihr zur Vorbereitung weitere seriöse Quellen eurer Wahl nutzen.

Die\*der Sachverständige\*r `L. G.` soll im Rahmen der Verhandlung sowohl von euch als Verteidigung als auch von der Staatsanwaltschaft befragt werden. Dementsprechend ist es wichtig das Sachverständige\*r `L. G.` einen sehr guten Überblick über die von euch verwendeten Beweismittel hat.

## #1 Haben wir einen freien Willen? {#def-ev1}

**Auszug aus dem Aufsatz "Haben wir einen freien Willen?" von Benjamin Libet [-@Libet2004]**

> „Ich habe mich dieser Frage auf experimentelle Weise genähert. Freien Willenshandlungen geht eine spezifische elektrische Veränderung im Gehirn voraus (das ›Bereitschaftspotentiak‹, BP), das 550 ms vor der Handlung einsetzt. Menschliche Versuchspersonen wurden sich der Handlungsintention 350-400 ms nach Beginn von BP bewußt, aber 200 ms vor der motorischen Handlung. Der Willensprozeß wird daher unbewußt eingeleitet.‟ (S.268)

## #2 Warum noch debattieren? {#def-ev2}

**Auszüge aus dem Aufsatz "Warum noch debattieren? Determinismus als Diskurskiller" von Gerhard Kaiser [-@Kaiser2004]**

> „Aber derselbe Wolf Singer, der von Komplementarität spricht, verwendet fortgesetzt grenzüberschreitend das Kausalitätsschema (S. 29), nennt Gedanken »Folge neuronaler Prozesse« (S. 15) und weitet die deterministische Position sogar dahin aus, daß »auch die kulturelle Umwelt determiniert« (S. 23).‟ (S. 263)

> „Willensfreiheit ist relativ - menschliche Freiheit ist nie so gedacht worden, daß dem Menschen alle je denkbaren Optionen auch offenstehen. Sie findet statt innerhalb eines individuellen und historischen Ermöglichungs- und Bedingungsrahmens. Und sie ist, jedenfalls auf der Stufe des reflexiven Bewußtseins, ein Spezifikum des Menschen.‟ (S. 265)

## #3 Infektion des Geistes {#def-ev3}

**Auszüge aus dem Aufsatz "Infektion des Geistes. Über philosophische Kategorienfehler" von Gerd Kempermann [-@Kempermann2004]**

> „Der freie Wille gehört wie die Menschenwürde in die Karegorie der Konstrukte, die Zuschreibungen sind. Freier Wille bleibt schon in der Eigenwahrnehmung unscharf. Man mag prinzipiell viel auf die eigene Autonomie halten, um sie doch in schwierigen Situationen, nicht nur in Strafverfahren, bereitwillig über Bord zu werfen und auf biologische Entlastungsgründe zurückzugreifen. Wir sind uns unserer Natur und der Abhängigkeit von ihr durchaus bewußt. Aber das befreit uns nicht davon, verantwortlich zu handeln. Denn es ist ja nicht nur Natur in uns.‟ (S. 236)

> „Wenn man in Zusammenhängen, die wir bisher der Psyche zugeschrieben haben, die Erkenntnisse der Biologie zuläßt, brechen nicht gleich die moralischen Fundamente des Abendlandes weg. Durch Berücksichtigung der »Natur des Menschen« gelingt es oft erst, zu wirklich menschlichen Lösungen zu gelangen. Die forensische Psychiatrie beschäftigt sich seit langem mit diesen Fragen, und auch sie lernt nicht nur durch soziopsychologische Forschung, sondern auch durch Neurobiologie dazu.‟ (S. 237)

> „Die bestimmende Interaktion zwischen Natur und persönlicher Lebensgeschichte gilt selbstverständlich nicht nur für die Psychiatrie. Bei Herzinfarkten, Typ-II-Diabetes und bestimmten Krebsformen ist das Zusammenspiel von Disposition und Lebensführung Allgemeingut geworden. Was ist Lebensführung anderes als der persönliche, »freie« Umgang mit Disposition, das verantwortliche Leben der eigenen Natur?‟ (S. 238)

> „Eine Ethik können nur Menschen haben. Biologische Fakten anzuerkennen heißt nicht, der Verantwortung ledig zu sein, eine solche Ethik zu entwickeln.‟ (S. 239)

## #4 Ick bün all da {#def-ev4}

**Auszüge aus dem Aufsatz "Ick bün all da. Ein neuronales Erregungsmuster" von Reinhard Brandt [-@Brandt2004]**

> „» Wie sünd all da!« Mit ihren raffinierten Horchgeräten und Kernspintomographen hören die Forscher das homerische Gelächter der Zellen über den verwirrten Geist und den Willen der Menschen, die sich frei und selbständig dünken und doch nur ausführen, was im grauen Netzwerk der Zellen zuvor festgelegt wurde. Der Geist gleicht der Fliege, die auf einem Wagenrad sitzt und sich einbildet, das Rad zu bewegen.‟ (S. 171)

> „Und das Gefühl der Freiheit, das unweigerlich unsere Entschlüsse und die ihnen folgenden Handlungen begleitet, auch dieses unvermeidliche Gefühl ist wohl nichts anderes als eine Illusion, die aus der Retrospektive auch meistens verschwindet: Man hätte damals eben doch nicht anders handeln können. Das Freiheitsgefühl scheint nur der blinde Fleck im Auge zu sein, der uns die determinierenden Ursachen nicht sehen läßt. Im übrigen verhalten wir uns grundsätzlich so, daß wir nicht an die Freiheit der Menschen glauben; wenn das freie Wahlvolk anders stimmt oder der freie Nachbar anders handelt, als erwartet, so fragen wir nach den Ursachen und Motiven wie beim Ausfall von Gas und Strom oder beim auffälligen Verhalten von Hunden und Katzen. Du hättest anders handeln können, das sagen wir bevorzugt, wenn es um Schuldzuweisungen geht, aber sonst sind wir »Deterministen«: Von dem und dem war nichts anderes zu erwarten; Sokrates lügt eben nicht, der kann nicht anders.‟ (S. 171-172)

> „Wir sehen Optisches, wir hören Akustisches, wir ertasten Haptisches - aber was das jeweils für Dinge sind, die wir da sehen und hören und ertasten, darüber können uns die Sinne nicht mehr belehren. Wir meinen, wir würden einen im Wasser gebrochenen Stab sehen, der dann doch gerade ist. Aber das ist eine Illusion des Skeptikers: Was wir völlig richtig sehen, ist eine graue gebrochene breitere Linie; daß es ein Stab ist, gar ein gebrochener Stab, dazu schweigt der Sehsinn pflichtgemäß, denn von Stäben weiß er nichts. Was ein Stab ist, sagt uns der Verstand.
>
> Blickt der Neurologe ins Feld, so sieht er keinen Igel und keinen Hasen, sondern bestimmte Formen und Farben und Bewegungen, die er, ein igel- und hasengewohnter Abendländer, richtig erkennt. Vielleicht hielt er den Hasen zuerst für ein Kaninchen und ließ sich durch einen Spezialisten, etwa einen Jäger, dankbar korrigieren: *Sehen* läßt sich nicht, was ein Hase und was ein Kaninchen ist. Im Labor sieht er etwas Graues, das sich weich und feucht anfühlt und stumm ist; als wissenschaftlicher Spezialist erkennt er dieses Etwas als Gehirn; mit seinen Apparaten identifiziert er Synapsen und Zellen, immer im Zusammenspiel von Sinnesinformationen und hochspezialisierten Erkenntnisleistungen. Seine Berichte über die Ergebnisse verzerren, aber sie vereinfachen auch die Situation durch die Benutzung der schon genannten Illusion: Er tut so, als könnte er die Zeilen als Zellen und die Vernetzungen als Vernetzungen *sehen* - davon kann zwar die Rede sein, der Sache nach ist diese Redeform jedoch unhaltbar: Zellen und Vernetzungen kann man so wenig sehen wie Telefone und Computer, Stäbe und Sonnen und Monde.‟ (S. 173)

> „Jede mitteilbare wahre oder falsche Erkenntnis setzt sich aus Urteilen zusammen wie z. B. »Alles Wissen, über das ein Gehirn verfügt, residiert in seiner funktionellen Architektur«; ein Urteil ist im einfachsten Fall die Einheitsverknüpfung von Subjekt und Prädikat, wobei diese Verknüpfung notwendig entweder bejahend oder verneinend ist (hier also: » Nicht alles Wissen, [...]« oder »[...] residiert nicht in seiner Architektur«). Die Verneinung vereint Subjekt und Prädikat im Urteil und behauptet zugleich deren Trennung. Die gegen die Vorstellung vom Primat der Materie oder des Gehirns gegenüber dem Geist gerichtete These lautet: In keiner Gehirnzelle und in keiner Synapse hat man und wird man das Äquivalent eines Urteils, besonders keine Verneinung entdecken. Wer je im Gehirn eine Verneinung auffindet, dem verpfände ich alle Synapsen, die an dieser Zeile beteiligt sind (beim Milliardenaufkommen wird das ja zu verkraften sein). Solange eine Urteils- oder Erkenntnisbildung und besonders eine Verneinung nicht entdeckt wurden, läßt sich der Geist nicht auf noch so dynamische und demokratisch vernetzte Prozesse des Gehirns zurückführen. Sie bieten notwendige, aber keine hinreichenden Bedingungen für den Geist, der nein sagen kann und mit seinem ersten Nein ins Dasein sprang.‟ (S. 175)

## #5 You don't have free will, but don't worry

Ein Video von [Dr. Sabine Hossenfelder](https://sabinehossenfelder.com "Homepage von Dr. Sabine Hossenfelder") (theoretische Physikerin), in dem sie erklärt warum die Idee des freien Willen mit den derzeit bekannten Naturgesetzen unvereinbar ist [@Hossenfelder2020].

```{r echo=FALSE, out.extra='style="border: none;"', out.width='99%'}


knitr::include_url('https://www.youtube.com/embed/zpU_e3jh_FY')

```

[Video: "You don't have free will, but don't worry."](https://www.youtube.com/watch?v=zpU_e3jh_FY "Video: "You don't have free will, but don't worry."")

## Weitere Quellen {#def-more}

-   Aufsatz „Gründe zählen. Über einige Schwierigkeiten des Bionaturalismus‟ von Lutz Wingert [-@Lutz2004]

-   Aufsatz „Verschaltungen legen uns fest: Wir sollten aufhören, von Freiheit zu sprechen‟ von Wolf Singer [-@Singer2004]

-   Aufsatz „Der entlarvte Ruck. Was sagt Kant den Gehirnforschern‟ von Otfried Höffe [-@Höffe2004]
