# Ergebnisse der Seminarsitzung {#results}

## Beweisanträge der Staatsanwaltschaft {#pr-ev}

> "Die Voraussetzungen, die notwendig sind um einen Angeklagten des Mordes schuldig zu sprechen, waren bei der Tat vollständig erfüllt. Zum einen lag der Aspekt der Heimtücke vor. Sigmund F. war zum Zeitpunkt der Tat in einer Besprechung mit Carl-Gustaf J. und dementsprechend wehrlos. Zum anderen zeugte das Tötungsdelikt von besonderer Grausamkeit."

> "Die Quantenphysik zeigt uns das wahrer Zufall existiert. Daher kann es keinen Determinismus geben. Dementsprechend ist davon auszugehen, dass der freie Willen existiert. Die Aussage „Alles ist determiniert" hat keinen Wahrheitsgehalt, da laut des Determinismus bereits die Tätigung dieser Aussage determiniert gewesen sein muss. Dies ist ein Zirkelschluss."

> "Menschliches Verhalten basiert sowohl auf bewussten als auch auf unbewussten Prozessen. Im Rahmen jener bewussten Prozesse, die zu einem bestimmten Verhalten führen, ist es möglich, sich zwischen richtig und falsch zu entscheiden. Dementsprechend hätte sich der Angeklagte spätestens im Zuge der Ausführung der Tat mittels einer Veto-Entscheidung gegen die Vollendung der Tat entscheiden können."

> "Einen freien Willen gibt es laut Pauen dann, wenn die Handlung autonom ist. Dies ist klar gegeben. Daniel B. hat autonom die Entscheidung getroffen in die Vergangenheit zu reisen und hat die Tat bewusst geplant (Urheberschaft)."

> "Daniel B. ist „noch" kein Mehrfachtöter. Die Gefahr, dass er ohne Strafe ein weiteres Vergehen begehen würde, ist jedoch hoch. Die Wahrscheinlichkeit einer erneuten Straffälligkeit liegt bei ca. 35%. Besonders Männer sind gefährdet. Deshalb ist eine Gefängnisstrafe unabdingbar. Für die Gesellschaft ist es nicht tragbar, wenn er noch frei rumläuft."

> "Außerdem ist die Grundlage unseres Rechtssystem, dass der Mensch einen freien Willen hat. Dies impliziert, dass der Angeklagte für schuldig gesprochen werden muss. Auch wenn der Angeklagte keinen freien Willen hat, sollte er schuldig gesprochen werden. Es ist notwendig, zumindest die Illusion des freien Willens in unserer Gesellschaft aufrechtzuerhalten."

### Aussagen des Sachverständigen Immanuel Kant {#pr-expert-statement}

> -   "Menschen sind autonom, i.e. selbstbestimmt."
>
>     -   "Maxime, nach der Mensch selbst handelt"
>
> -   "Determinismus ist trotzdem gegeben."
>
> -   "Willensfreiheit und Determinismus stehen nicht im Widerspruch."

### Kreuzverhör des Sachverständigen Benjamin Libet {#pr-expert-cross}

> -   "Die Studie weist große methodische Mängel auf."
>
> -   "Die Instruktion an die Teilnehmenden war: »Schauen Sie auf die Uhr, wenn sie das Gefühl haben, sie möchten gleich die Hand heben.«"
>
>     -   "Was für ein Gefühl?"
>
>     -   "Wo bzw. wann genau beginnt dieses Gefühl?"
>
>     -   "Geht dem Gefühl ein Wahrnehmungsprozess voraus?"
>
> -   "Es gibt auch andere Studien, die zeigen, dass es zwar keinen freien Willen gibt, aber ein „freies Veto" zwischen Bereitschaftspotential und Handlung: Free Won't (Mord abbrechen/nicht begehen)."

## Beweisanträge der Verteidigung {#def-ev}

> "*In dubio pro reo* - Im Zweifel für den Angeklagten. Er ist unschuldig bis zum Beweis, dass er einen freien Willen hatte. Man kann freien Willen nicht sehen, anfassen, irgendwie erfahren und daher auch nicht nachweisen. Es gibt keine naturwissenschaftliche, philosophische, etc. stichhaltigen Belege für die Existenz des freien Willens. Wir wollen es nur nicht wahrhaben, dass wir keinen freien Willen haben, weil sich das besser anfühlt, wenn ich jemanden verantwortlich machen kann."

> "Die Idee von Freiheit existiert, aber das heißt ja nicht, dass der freie Wille existiert."

> "Es ist in der Tat so, dass Determinismus existiert. Wir können nur nicht die Zukunft berechnen, weil wir nicht die Mittel dafür besitzen. In der Theorie wäre es jedoch möglich."

> "Der freie Wille ist nur ein Produkt unserer existentiellen Angst. Mit ihm ist es leichter zu leben."

> "Die eigene Willensfreiheit ist nur eine Illusion. Wenn etwas aus Zufall passiert, dann konnte es auch nicht durch den freien Willen beeinflusst werden."

> "Der Angeklagte konnte nicht aus freiem Willen handeln, da es keinen freien Willen gibt. Dementsprechend ist er für sein Handeln nicht verantwortlich und kann daher auch nicht schuldig gesprochen werden."

> "Auch wenn er einen freien Willen haben sollte, ist dieser aufgrund von einer sicherlich vorhandenen psychischen Erkrankung eingeschränkt."

### Aussagen des Sachverständigen Benjamin Libet {#def-expert-statement}

> -   "Freier Wille wurde experimentell getestet: Entdeckung eines Bereitschaftspotentials vor der Entscheidung eine Handlung auszuführen."
>
> -   "Daraus resultiert, dass es keinen freien Willen geben kann. Daher ist Daniel B. schuldlos."

### Kreuzverhör des Sachverständigen Immanuel Kant {#def-expert-cross}

> -   "Allein der Glauben an den Freien Willen reicht nicht. Wo sind die empirischen Beweise?"
>
> -   "Nur weil Mensch etwas denken kann, heißt das nicht, dass es das auch gibt."
>
> -   "Kant kann nicht beweisen, dass Freiheit existiert. Lediglich: Idee der Freiheit"

## Plädoyer der Staatsanwaltschaft {#pr-plea}

> "Die Annahme der Verteidigung beruht ausschließlich auf dem Argument, dass es keinen freien Willen gibt, da alles determiniert ist.
>
> Sachverständiger Kant hat jedoch betont, dass es auch zufällige Ereignisse gibt. Ein freier Wille ist also nicht ausgeschlossen. Sachverständiger Libet muss bei seinem angeblichen Beweis, dass es keinen freien Willen gibt, einige essentielle Fehler eingestehen. Er ist nicht im Recht, da seine Studie methodische, methologische, logische und theoretische Mängel hat.
>
> In unserer Gesellschaft und vor allem auch in unserem Rechtssystem wird angenommen, dass es einen freien Willen gibt.
>
> Nach gegebener Sachlage, unter Annahme der Existenz des freien Willens laut Gesetzbuch, unter Berücksichtigung der Erfüllung aller Kriterien des Mordes und der erhöhten Gefahr einer erneuten Straffälligkeit, sprechen wir uns deutlich für einen Schuldspruch aus."

## Plädoyer der Verteidigung {#def-plea}

> "Naturwissenschaftliche, philosophische und psychologische Begründungen zielen alle auf das gleiche ab: Es gibt keinen freien Willen. In der Physik gilt Determinismus schon als bewiesen. Experimente, wie das Libet-Experiment, muss man nicht kritisieren.
>
> Wir leben nicht in einer Welt, in der man prophylaktisch jemanden wegsperren kann. Die Existenz des freien Willens kann nicht bewiesen werden.
>
> In Zweifel für den Angeklagten.
>
> Daniel B. sollte nicht schuldig gesprochen werden."

## Urteilsverkündung {#sentencing}

> "Die Richter\*innen sind **einstimmig für einen Schuldspruch**.
>
> Die Begründungen hierfügen basieren zum einen auf dem Argument, dass es weder Beweise für noch gegen den freien Willen gibt. Ein Schuldspruch ist jedoch für die gesellschaftliche Ordnung notwendig.
>
> Auch wenn Determinismus vorliegt, können wir nicht bewerten, ob Daniel B. nochmal morden wird oder nicht (weil dies nicht berechnet bzw. vorhergesagt werden kann). Ein Schuldspruch ist notwendig, damit Mensch sicherstellen kann, dass Daniel B. keine Gefahr für die Öffentlichkeit darstellt. Daniel B. sollte zuallererst unter psychiatrische Beobachtung gestellt werden. In der Folge sollte ein Gutachten erstellt werden, das eine Aussage darüber trifft, welche Gefahr von Daniel B. ausgeht."
